---
title: Industry Internships
---

## Sentient Labs, United Arab Emirates
**UX Engineer and Designer** (Jul. 2022 - Aug. 2022) <br>

  - **Orchestrated** research on Unmanned Surface Vehicles (USVs), articulating their need and design requirements, advancing the understanding of USV applications which helped with the USV creation at the company.
  - **Evaluated** research data collected on USVs to identify fallacies and methodologies adopted in development, enhancing future design strategies which improved construction efficiency by 12%.

## Ojo, Remote - Dubai, UAE
**Student Brand Ambassador** (May. 2020 - Aug. 2020) <br>

  - **Executed** tasks and conducted user research by interviewing students of varied ages, enhancing the platform's impact through user-centered design increasing user engagement by 36%.
  - **Coordinated** with multiple project members and students to develop solutions for building software to guide students in their careers through guided user studies. The enrollment in the program increased from 130 to 347.
  - **Formulated** a user-centered business model as a group project, understanding business needs and future goals, driving the startup's progress towards its objectives which was implemented by the company, increasing quarterly company revenue by 6%.
